apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::145072103577:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1VZWOZXQFKVSD
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::145072103577:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-06T17:47:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1714"
  uid: 250ad11f-3891-4626-8f1c-63418cd4ccab
